-- AlterTable
ALTER TABLE `ReturnRequests` ADD COLUMN `adminNote` TEXT NULL,
    MODIFY `status` ENUM('PENDING', 'APPROVED', 'SHIPPING', 'RECEIVED', 'INSPECTING', 'COMPLETED', 'REJECTED', 'CANCELLED') NOT NULL DEFAULT 'PENDING';
